backend:
  name: github
  repo: trobins15/cmts_jekyll
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: assets
public_folder: /images/uploads
#publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Posts
    name: posts
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Web Pages"
    name: Pages
    label_singular: Page
    folder: _pages/
    create: true
    preview_path: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sidenav', name: 'sidenav', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Manual PDF",
         name: "manual_pdf",
         widget: "file"
         }
  - label: "Documents"
    name: Documents
    label_singular: Document
    folder: _assets/documents
    create: true
    preview_path: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sidenav', name: 'sidenav', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Manual PDF",
         name: "manual_pdf",
         media_folder: assets/uploads/documents,
         widget: "file"
         }

